[build]
  command = "npm run build"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/static/js/*"
  [headers.values]
    Content-Type = "application/javascript"
